### ISSUE TITLE
WUT?!

### ISSUE THREAD

**Issue by KOLANICH** [Debianov/review_me#1]

**Comment by Debianov** [comment]
Код временно убран по решению товарища Майора из какого-то отдела, вроде "К" называется. Не говорят пока, когда вернут.

**Comment by KOLANICH** [comment]
Как же они вас нашли, под маской Гая Фокса и под фейковой фамилией?

И, если это не секрет государственной важности, какой именно репозиторий привёл вас в мой профиль?

**Comment by Debianov** [comment]
Вычислили через трассировку лучей (секретная технология).

[Репозиторий](https://github.com/tlwg/libdatrie/tree/d1dfdb831093892541cae46eba82c46aec94f726), по которому нашёл вас.

**Comment by KOLANICH** [comment]
Спасибо.
